-- ============================================================================
-- Stackd Security & Performance Migrations
-- ============================================================================
-- Security patches and performance optimizations
-- Run this last: psql -f supabase/04_migrations.sql
-- 
-- This file contains:
-- - Dropped unused indexes (performance)
-- - Security hardening patches
-- ============================================================================

-- ============================================================================
-- DROP UNUSED INDEXES
-- ============================================================================
-- idx_votes_user_id is redundant - covered by unique(user_id, post_id) constraint
-- Dropping saves storage and improves write performance
-- ============================================================================
drop index if exists idx_votes_user_id;

-- ============================================================================
-- SECURITY: ENABLE LEAKED PASSWORD PROTECTION
-- ============================================================================
-- NOTE: This requires Supabase Dashboard or CLI configuration
-- 
-- To enable via Supabase CLI:
--   supabase auth password-leaked-protection enable
--
-- Or via Dashboard:
--   1. Go to Authentication → Providers → Email
--   2. Enable "Enable leaked credentials protection"
--
-- This feature checks passwords against HaveIBeenPwned database
-- to prevent users from using compromised passwords.

-- ============================================================================
-- MATERIALIZED VIEW API ACCESS
-- ============================================================================
-- The trending_tags materialized view is intentionally accessible via API
-- for the frontend to fetch trending tags server-side.
-- 
-- If you want to revoke API access, uncomment below:
-- revoke select on trending_tags from anon, authenticated;

-- ============================================================================
-- VERIFICATION: CHECK RLS POLICIES
-- ============================================================================
-- Uncomment to verify RLS is enabled on all tables:
--
-- select 
--   schemaname,
--   tablename,
--   policyname,
--   permissive,
--   roles,
--   cmd,
--   qual
-- from pg_policies
-- where schemaname = 'public'
-- order by tablename, policyname;

-- ============================================================================
-- VERIFICATION: CHECK FUNCTION SECURITY SETTINGS
-- ============================================================================
-- Uncomment to verify functions have secure search_path:
--
-- select 
--   proname,
--   prosrc,
--   pronsecurity,
--   prokind,
--   lanname,
--   pg_get_functiondef(oid)
-- from pg_proc p
-- join pg_language l on p.prolang = l.oid
-- where pronamespace = 'public'::regnamespace
--   and proname in ('handle_new_user', 'update_post_score', 'refresh_trending_tags', 'refresh_trending_tags_trigger');

-- ============================================================================
-- VERIFICATION: CHECK INDEX USAGE
-- ============================================================================
-- Uncomment to check index usage (run after some traffic):
--
-- select 
--   schemaname,
--   tablename,
--   indexname,
--   idx_scan,
--   idx_tup_read,
--   idx_tup_fetch
-- from pg_stat_user_indexes
-- where schemaname = 'public'
-- order by idx_scan asc;
